language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
addons:
  chrome: stable
  firefox: latest
services:
- xvfb

before_install:
- npm install
script:
- npm run build:prod
- npm run test:unit
  
