minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - "@adobe/alloy"
  - "@adobe/reactor-sandbox"
  - "@adobe/reactor-turbine"
  - "@adobe/reactor-turbine-schemas"
verifyDepsBeforeRun: warn
ignoredBuiltDependencies:
  - core-js
  - lmdb
  - msgpackr-extract
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - puppeteer
overrides:
  "eslint": "^9.35.0"
  "strip-comments": "^2.0.1"
