/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2016 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property
* laws, including trade secret and copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/

// Array instead of object because order is important.
export default [
  { value: 'USD', label: 'United States Dollar' },
  { value: 'AED', label: 'United Arab Emirates Dirhams' },
  { value: 'AFA', label: 'Afghanistan Afghanis' },
  { value: 'ALL', label: 'Albania Leke' },
  { value: 'AMD', label: 'Armenia Drams' },
  { value: 'ANG', label: 'Netherlands Antilles Guilders' },
  { value: 'AOA', label: 'Angola Kwanza' },
  { value: 'ARS', label: 'Argentina Pesos' },
  { value: 'AUD', label: 'Australia Dollars' },
  { value: 'AWG', label: 'Aruba Guilders' },
  { value: 'AZM', label: 'Azerbaijan Manats' },
  { value: 'BAM', label: 'Bosnia and Herzegovina Convertible Marka' },
  { value: 'BBD', label: 'Barbados Dollars' },
  { value: 'BDT', label: 'Bangladesh Taka' },
  { value: 'BGN', label: 'Bulgaria Leva' },
  { value: 'BHD', label: 'Bahrain Dinars' },
  { value: 'BIF', label: 'Burundi Francs' },
  { value: 'BMD', label: 'Bermuda Dollars' },
  { value: 'ILS', label: 'Israel New Shekels' },
  { value: 'IMP', label: 'Isle of Man Pounds' },
  { value: 'INR', label: 'India Rupees' },
  { value: 'IQD', label: 'Iraq Dinars' },
  { value: 'IRR', label: 'Iran Rials' },
  { value: 'ISK', label: 'Iceland Kronur' },
  { value: 'JEP', label: 'Jersey Pounds' },
  { value: 'JMD', label: 'Jamaica Dollars' },
  { value: 'JOD', label: 'Jordan Dinars' },
  { value: 'JPY', label: 'Japan Yen' },
  { value: 'KES', label: 'Kenya Shillings' },
  { value: 'KGS', label: 'Kyrgyzstan Soms' },
  { value: 'KHR', label: 'Cambodia Riels' },
  { value: 'KMF', label: 'Comoros Francs' },
  { value: 'KPW', label: 'North Korea Won' },
  { value: 'KRW', label: 'South Korea Won' },
  { value: 'KWD', label: 'Kuwait Dinars' },
  { value: 'KYD', label: 'Cayman Islands Dollars' },
  { value: 'SEK', label: 'Sweden Kronor' },
  { value: 'SGD', label: 'Singapore Dollars' },
  { value: 'SHP', label: 'Saint Helena Pounds' },
  { value: 'SIT', label: 'Slovenia Tolars' },
  { value: 'SKK', label: 'Slovakia Koruny' },
  { value: 'SLL', label: 'Sierra Leone Leones' },
  { value: 'SOS', label: 'Somalia Shillings' },
  { value: 'SPL', label: 'Seborga Luigini' },
  { value: 'SRG', label: 'Suriname Guilders' },
  { value: 'STD', label: 'Sao Tome and Principe Dobras' },
  { value: 'SVC', label: 'El Salvador Colones' },
  { value: 'SYP', label: 'Syria Pounds' },
  { value: 'SZL', label: 'Swaziland Emalangeni' },
  { value: 'THB', label: 'Thailand Baht' },
  { value: 'TJS', label: 'Tajikistan Somoni' },
  { value: 'TMM', label: 'Turkmenistan Manats' },
  { value: 'TND', label: 'Tunisia Dinars' },
  { value: 'TOP', label: 'Tonga Pa\'anga' },
  { value: 'BND', label: 'Brunei Dollars' },
  { value: 'BOB', label: 'Bolivia Bolivianos' },
  { value: 'BRL', label: 'Brazil Reais' },
  { value: 'BSD', label: 'Bahamas Dollars' },
  { value: 'BTN', label: 'Bhutan Ngultrum' },
  { value: 'BWP', label: 'Botswana Pulas' },
  { value: 'BYR', label: 'Belarus Rubles' },
  { value: 'BZD', label: 'Belize Dollars' },
  { value: 'CAD', label: 'Canada Dollars' },
  { value: 'CDF', label: 'Congo/Kinshasa Francs' },
  { value: 'CHF', label: 'Switzerland Francs' },
  { value: 'CLP', label: 'Chile Pesos' },
  { value: 'CNY', label: 'China Yuan Renminbi' },
  { value: 'COP', label: 'Colombia Pesos' },
  { value: 'CRC', label: 'Costa Rica Colones' },
  { value: 'CSD', label: 'Serbia Dinars' },
  { value: 'CUP', label: 'Cuba Pesos' },
  { value: 'CVE', label: 'Cape Verde Escudos' },
  { value: 'CYP', label: 'Cyprus Pounds' },
  { value: 'CZK', label: 'Czech Republic Koruny' },
  { value: 'DJF', label: 'Djibouti Francs' },
  { value: 'DKK', label: 'Denmark Kroner' },
  { value: 'DOP', label: 'Dominican Republic Pesos' },
  { value: 'DZD', label: 'Algeria Dinars' },
  { value: 'EEK', label: 'Estonia Krooni' },
  { value: 'EGP', label: 'Egypt Pounds' },
  { value: 'ERN', label: 'Eritrea Nakfa' },
  { value: 'ETB', label: 'Ethiopia Birr' },
  { value: 'EUR', label: 'Euro' },
  { value: 'FJD', label: 'Fiji Dollars' },
  { value: 'FKP', label: 'Falkland Islands Pounds' },
  { value: 'GBP', label: 'United Kingdom Pounds' },
  { value: 'GEL', label: 'Georgia Lari' },
  { value: 'GGP', label: 'Guernsey Pounds' },
  { value: 'GHC', label: 'Ghana Cedis' },
  { value: 'GIP', label: 'Gibraltar Pounds' },
  { value: 'GMD', label: 'Gambia Dalasi' },
  { value: 'GNF', label: 'Guinea Francs' },
  { value: 'GTQ', label: 'Guatemala Quetzales' },
  { value: 'GYD', label: 'Guyana Dollars' },
  { value: 'HKD', label: 'Hong Kong Dollars' },
  { value: 'HNL', label: 'Honduras Lempiras' },
  { value: 'HRK', label: 'Croatia Kuna' },
  { value: 'HTG', label: 'Haiti Gourdes' },
  { value: 'HUF', label: 'Hungary Forint' },
  { value: 'IDR', label: 'Indonesia Rupiahs' },
  { value: 'KZT', label: 'Kazakhstan Tenge' },
  { value: 'LAK', label: 'Laos Kips' },
  { value: 'LBP', label: 'Lebanon Pounds' },
  { value: 'LKR', label: 'Sri Lanka Rupees' },
  { value: 'LRD', label: 'Liberia Dollars' },
  { value: 'LSL', label: 'Lesotho Maloti' },
  { value: 'LTL', label: 'Lithuania Litai' },
  { value: 'LVL', label: 'Latvia Lati' },
  { value: 'LYD', label: 'Libya Dinars' },
  { value: 'MAD', label: 'Morocco Dirhams' },
  { value: 'MDL', label: 'Moldova Lei' },
  { value: 'MGA', label: 'Madagascar Ariary' },
  { value: 'MKD', label: 'Macedonia Denars' },
  { value: 'MMK', label: 'Myanmar Kyats' },
  { value: 'MNT', label: 'Mongolia Tugriks' },
  { value: 'MOP', label: 'Macau Patacas' },
  { value: 'MRO', label: 'Mauritania Ouguiyas' },
  { value: 'MTL', label: 'Malta Liri' },
  { value: 'MUR', label: 'Mauritius Rupees' },
  { value: 'MVR', label: 'Maldives Rufiyaa' },
  { value: 'MWK', label: 'Malawi Kwachas' },
  { value: 'MXN', label: 'Mexico Pesos' },
  { value: 'MYR', label: 'Malaysia Ringgits' },
  { value: 'MZM', label: 'Mozambique Meticais' },
  { value: 'NAD', label: 'Namibia Dollars' },
  { value: 'NGN', label: 'Nigeria Nairas' },
  { value: 'NIO', label: 'Nicaragua Gold Cordobas' },
  { value: 'NOK', label: 'Norway Kroner' },
  { value: 'NPR', label: 'Nepal Rupees' },
  { value: 'NZD', label: 'New Zealand Dollars' },
  { value: 'OMR', label: 'Oman Rials' },
  { value: 'PAB', label: 'Panama Balboas' },
  { value: 'PEN', label: 'Peru Nuevos Soles' },
  { value: 'PGK', label: 'Papua New Guinea Kina' },
  { value: 'PHP', label: 'Philippines Pesos' },
  { value: 'PKR', label: 'Pakistan Rupees' },
  { value: 'PLN', label: 'Poland Zlotych' },
  { value: 'PYG', label: 'Paraguay Guarani' },
  { value: 'QAR', label: 'Qatar Riyals' },
  { value: 'ROL', label: 'Romania Lei' },
  { value: 'RUR', label: 'Russia Rubles' },
  { value: 'RWF', label: 'Rwanda Francs' },
  { value: 'SAR', label: 'Saudi Arabia Riyals' },
  { value: 'SBD', label: 'Solomon Islands Dollars' },
  { value: 'SCR', label: 'Seychelles Rupees' },
  { value: 'SDD', label: 'Sudan Dinars' },
  { value: 'SRD', label: 'Suriname Dollars' },
  { value: 'TRL', label: 'Turkey Liras' },
  { value: 'TTD', label: 'Trinidad and Tobago Dollars' },
  { value: 'TVD', label: 'Tuvalu Dollars' },
  { value: 'TWD', label: 'Taiwan New Dollars' },
  { value: 'TZS', label: 'Tanzania Shillings' },
  { value: 'UAH', label: 'Ukraine Hryvnia' },
  { value: 'UGX', label: 'Uganda Shillings' },
  { value: 'UYU', label: 'Uruguay Pesos' },
  { value: 'UZS', label: 'Uzbekistan Sums' },
  { value: 'VEB', label: 'Venezuela Bolivares' },
  { value: 'VND', label: 'Vietnam Dong' },
  { value: 'VUV', label: 'Vanuatu Vatu' },
  { value: 'WST', label: 'Samoa Tala' },
  { value: 'XAF', label: 'Communauté Financière Africaine Francs B' },
  { value: 'XAG', label: 'Silver Ounces' },
  { value: 'XAU', label: 'Gold Ounces' },
  { value: 'XCD', label: 'East Caribbean Dollars' },
  { value: 'XDR', label: 'International Monetary Fund Special Draw' },
  { value: 'XOF', label: 'Communauté Financière Africaine Francs B' },
  { value: 'XPD', label: 'Palladium Ounces' },
  { value: 'XPF', label: 'Comptoirs Français du Pacifique Francs' },
  { value: 'XPT', label: 'Platinum Ounces' },
  { value: 'YER', label: 'Yemen Rials' },
  { value: 'ZAR', label: 'South Africa Rand' },
  { value: 'ZMK', label: 'Zambia Kwacha' },
  { value: 'ZWD', label: 'Zimbabwe Dollar' }
];
