apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 3
metadata:
  name: Alloy Reactor Extension
rootDir: ./
env:
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
  SAUCE_USERNAME: $SAUCE_USERNAME
  SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY
  EDGE_E2E_PRIVATE_KEY_CONTENTS: $EDGE_E2E_PRIVATE_KEY_CONTENTS
  EDGE_E2E_CLIENT_SECRET: $EDGE_E2E_CLIENT_SECRET
  REACTOR_IO_INTEGRATION_PRIVATE_KEY_CONTENTS: $REACTOR_IO_INTEGRATION_PRIVATE_KEY_CONTENTS
  REACTOR_IO_INTEGRATION_CLIENT_SECRET: $REACTOR_IO_INTEGRATION_CLIENT_SECRET
testcafe:
  version: 3.6.2
nodeVersion: "22"
speed: 1
pageLoadTimeout: 3000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
suites:

  - name: "Safari"
    browserName: "safari"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "macOS 13"

  - name: "Firefox"
    browserName: "firefox"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"

  - name: "Chrome"
    browserName: "chrome"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
