apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  sauceignore: .sauceignore
  concurrency: 5
defaults:
  timeout: 60m
metadata:
  name: Alloy Reactor Extension - Firefox
rootDir: ./
env:
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
  SAUCE_USERNAME: $SAUCE_USERNAME
  SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY
  SAUCE_CLIENT_TIMEOUT: 180s
  EDGE_E2E_PRIVATE_KEY_CONTENTS: $EDGE_E2E_PRIVATE_KEY_CONTENTS
  EDGE_E2E_CLIENT_SECRET: $EDGE_E2E_CLIENT_SECRET
  REACTOR_IO_INTEGRATION_PRIVATE_KEY_CONTENTS: $REACTOR_IO_INTEGRATION_PRIVATE_KEY_CONTENTS
  REACTOR_IO_INTEGRATION_CLIENT_SECRET: $REACTOR_IO_INTEGRATION_CLIENT_SECRET
testcafe:
  version: 3.6.2
nodeVersion: "20"
speed: 1
disablePageCaching: false
timeZone: New_York
pageRequestTimeout: 500
retryTestPages: false
quarantineMode: false
npm:
  dependencies:
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-sandbox"
    - "@adobe/reactor-query-string"
    - "@adobe/auth-token"
    - react
    - react-dom
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
suites:
  - name: "Component Tests"
    shard: concurrency
    esm: true
    browserName: "firefox"
    browserVersion: "latest"
    src:
      - "test/functional/specs/component/**/*.spec.mjs"
    platformName: "Windows 11"

  - name: "Runtime Tests"
    shard: concurrency
    esm: true
    browserName: "firefox"
    browserVersion: "latest"
    src:
      - "test/functional/specs/runtime/**/*.spec.mjs"
    platformName: "Windows 11"

  - name: "View Action Tests"
    shard: concurrency
    esm: true
    browserName: "firefox"
    browserVersion: "latest"
    src:
      - "test/functional/specs/view/actions/**/*.spec.mjs"
      - "test/functional/specs/view/runCommonExtensionViewTests.mjs"
    platformName: "Windows 11"

  - name: "View Configuration Tests"
    shard: concurrency
    esm: true
    browserName: "firefox"
    browserVersion: "latest"
    src:
      - "test/functional/specs/view/configuration/**/*.spec.mjs"
      - "test/functional/specs/view/runCommonExtensionViewTests.mjs"
    platformName: "Windows 11"

  - name: "View Data Elements Tests"
    shard: concurrency
    esm: true
    browserName: "firefox"
    browserVersion: "latest"
    src:
      - "test/functional/specs/view/dataElements/**/*.spec.mjs"
      - "test/functional/specs/view/runCommonExtensionViewTests.mjs"
    platformName: "Windows 11"
    screenResolution: "1024x768"