apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  sauceignore: .sauceignore
  concurrency: 1 
defaults:
  timeout: 30m
showConsoleLog: true
metadata:
  name: Alloy Reactor Extension - Safari
rootDir: ./
env:
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
  SAUCE_USERNAME: $SAUCE_USERNAME
  SAUCE_ACCESS_KEY: $SAUCE_ACCESS_KEY
  SAUCE_CLIENT_TIMEOUT: 180s
  EDGE_E2E_PRIVATE_KEY_CONTENTS: $EDGE_E2E_PRIVATE_KEY_CONTENTS
  EDGE_E2E_CLIENT_SECRET: $EDGE_E2E_CLIENT_SECRET
  REACTOR_IO_INTEGRATION_PRIVATE_KEY_CONTENTS: $REACTOR_IO_INTEGRATION_PRIVATE_KEY_CONTENTS
  REACTOR_IO_INTEGRATION_CLIENT_SECRET: $REACTOR_IO_INTEGRATION_CLIENT_SECRET
testcafe:
  version: 3.6.2
nodeVersion: "22"
speed: 1
disablePageCaching: false
timeZone: New_York
pageRequestTimeout: 60000
retryTestPages: false
quarantineMode: false
npm:
  dependencies:
    - testcafe
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-sandbox"
    - "@adobe/reactor-query-string"
    - "@adobe/auth-token"
    - react
    - react-dom
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
    - "@adobe/react-spectrum"
    - formik
    - yup
    - classnames
    - antd
suites:
  - name: "Safari"
    esm: true
    browserName: "safari"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.spec.mjs"
    platformName: "macOS 13"
    screenResolution: "1024x768"